---

- set_fact:
    __target_dir: "{{ unit_file_path[unit['destination']] | default(unit_file_path['primary']) }}"

- name: ensure directory presence
  file:
    path: "{{ __target_dir }}"
    mode: "u=rwX,go=r"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: establish units
  template:
    src: unit.j2 
    dest: "{{ __target_dir }}/{{ unit['name'] }}.{{ unit['type'] }}"
    mode: "u=rwx,go=r"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  notify: reload daemon
    
- name: load unit
  become: "{{ unit['destination'] != 'user' }}"
  when: "unit['type'] == 'service'"
  systemd:
    daemon_reload: yes
    name: "{{ unit['name'] }}"
    state: "{{ unit['state'] | default('started') }}"
    enabled: "{{ unit['enabled'] | default('yes') }}"
    masked: "{{ unit['masked'] | default('no') }}"
    scope: "{{ 'user' if unit['destination'] == 'user' else 'system' }}"

