---

- name: Converge
  hosts: all
  roles:
    - role: ansible-role-systemd
      vars:
        systemd_units:
          - name: "test service"
            type: service
            content: |
              [Unit]
              Description=Test service

              [Service]
              Type=oneshot
              ExecStart=/bin/echo "Just a test service"
              RemainAfterExit=yes
